// Generated by CoffeeScript 1.7.1
var Named;

Named = (function() {
  function Named(shell) {
    this.shell = shell;
    this.$named = $("<div />").addClass("named");
    this.$style = $("<style scoped />").html(".named .scope{\n  position: absolute;\n  border: none;\n  margin: 0px;\n  padding: 0px;\n  -webkit-user-select:none;\n  -webkit-tap-highlight-color:transparent;\n}\n.anchor,.select{\n  color:red;\n  cursor:pointer;\n}\n.anchor:hover,.select:hover{\n  background-color:violet;\n}");
    this.$named.append(this.$style);
    this.element = this.$named[0];
    this.scopes = [];
    this.currentScope = null;
  }

  Named.prototype.scope = function(scopeId) {
    if (arguments.length === 1) {
      if (!this.scopes[scopeId]) {
        this.scopes[scopeId] = new Scope(scopeId, this.shell);
      }
      this.currentScope = this.scopes[scopeId];
      this.$named.append(this.scopes[scopeId].element);
    }
    return this.currentScope;
  };

  return Named;

})();
