// Generated by CoffeeScript 1.7.1
var Scope;

Scope = (function() {
  function Scope(scopeId) {
    this.scopeId = scopeId;
    this.$scope = $("<div />").addClass("scope").css({
      "bottom": "0px",
      "right": (this.scopeId * 240) + "px"
    });
    this.$balloon = $("<div />").addClass("balloon");
    this.$scope.append(this.surface.canvas).append(this.$balloon);
  }

  Scope.prototype.surface = function() {};

  Scope.prototype.baloon = function() {};

  return Scope;

})();
